name = "next-ts-cloudflare-demo"
compatibility_date = "2026-04-29"

[[d1_databases]]
binding = "DB"
database_name = "next-ts-cloudflare-demo-d1"
database_id = "f682ca85-4576-4da4-a24c-bb2478cef682"

[[kv_namespaces]]
binding = "KV_CACHE"
id = "e56b9acd2d254dab8958828dfcee3a63"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "todo-images"

[vars]
CLOUDFLARE_ACCOUNT_ID = "5404ef0921988d8edf631a89a2a3db7c"
CLOUDFLARE_D1_DATABASE_ID = "f682ca85-4576-4da4-a24c-bb2478cef682"
CLOUDFLARE_KV_NAMESPACE_ID = "e56b9acd2d254dab8958828dfcee3a63"
CLOUDFLARE_R2_BUCKET_NAME = "todo-images"
CLOUDFLARE_R2_PUBLIC_BASE_URL = "https://pub-34d98ad79ee44bc489bf3747e7edcca9.r2.dev"
